# Common Temporal Compose setup. Use with include keyword.
#
# To use, add the following line to your compose.yaml file:
#
# include:
#   - ../temporal-compose.yaml
#
# This is also published to an OCI image and can be loaded:
#
# include:
#   - oci://ghcr.io/mrsimonemms/temporal-demos/temporal-compose
#
# This Temporal instance runs on ports 7234 (server) and 8080 (UI)

services:
  temporal:
    image: temporalio/temporal
    ports:
      - 7234:7233
      - 8080:8233
    command: server start-dev --ip 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "temporal operator cluster health"]
      interval: 10s
      timeout: 10s
      retries: 3
