# Common Temporal Compose setup. Use with include keyword. This is
# based on the official Temporal Docker Compose repo
# @link https://github.com/temporalio/docker-compose
#
# To use, add the following line to your compose.yaml file:
#
# include:
#   - ../temporal-compose.yaml
#
# This Temporal instance runs on ports 7234 (server) and 8080 (UI)

services:
  elasticsearch:
    image: elasticsearch:${ELK_VERSION:-9.0.3}
    environment:
      cluster.routing.allocation.disk.threshold_enabled: true
      cluster.routing.allocation.disk.watermark.low: 512mb
      cluster.routing.allocation.disk.watermark.high: 256mb
      cluster.routing.allocation.disk.watermark.flood_stage: 128mb
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      xpack.security.enabled: false
    ports:
      - 9200:9200
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120

  pgsql:
    image: postgres:${POSTGRESQL_VERSION:-16}
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal

  temporal:
    image: temporalio/auto-setup:${TEMPORAL_VERSION:-latest}
    environment:
      DB: postgres12
      DB_PORT: 5432
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development-sql.yaml
      ENABLE_ES: true
      ES_SEEDS: elasticsearch
      ES_VERSION: v7
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: pgsql
      POSTGRES_USER: temporal
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CLI_ADDRESS: temporal:7233
    depends_on:
      elasticsearch:
        condition: service_healthy
      pgsql:
        condition: service_started
    volumes:
      - ./dev/temporal:/etc/temporal/config/dynamicconfig
    ports:
      - 7234:7233

  temporal-ui:
    image: temporalio/ui:${TEMPORAL_UI_VERSION:-latest}
    environment:
      TEMPORAL_ADDRESS: temporal:7233
    depends_on:
      - temporal
    ports:
      - 8080:8080
